@startuml
Activity -> Activity: startActivityForResult
Activity -> Instrumentation:execStartActivity
Instrumentation -> ActivityManagerService: startActivity
ActivityManagerService -> ActivityManagerService: startActivityAsUser
ActivityManagerService -> ActivityStartController: obtainStarter
ActivityStartController --> ActivityManagerService: ActivityStarter
ActivityManagerService -> ActivityStarter: execute
ActivityStarter -> ActivityStarter: startActivity
ActivityStarter -> ActivityStarter: startActivityUnchecked
@enduml